server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
       # default_batch_fetch_size: 100 # in Query의 수 # 100 ~ maximum 1000개

logging:
  level:
    org.hibername.SQL: debug
    org.hibernate.type: trace